# Generated by Django 5.2.13 on 2026-04-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись ученика'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='students.student', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_owner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Куратор класса'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.studentclass', verbose_name='Класс ученика'),
        ),
    ]
