# Generated by Django 5.2.13 on 2026-04-17 17:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('level_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер уровня')),
                ('gender', models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Пол')),
                ('low_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальное значение для уровня')),
                ('middle_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Среднее значение для уровня')),
                ('high_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лучшее значение для уровня')),
                ('is_lower_better', models.BooleanField(default=False, help_text='Если отмечено, то меньшее значение считается лучшим (например, для времени)', verbose_name='Чем меньше, тем лучше')),
            ],
            options={
                'verbose_name': 'Уровень норматива',
                'verbose_name_plural': 'Уровни нормативов',
                'ordering': ['standard', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('has_numeric_value', models.BooleanField(help_text='Если True, то это физический норматив. Иначе - технический', verbose_name='Является ли это физическим или техническим нормативом')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Норматив',
                'verbose_name_plural': 'Нормативы',
            },
        ),
        migrations.CreateModel(
            name='StudentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('grade', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('value', models.FloatField(null=True, verbose_name='Значение')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Результат ученика',
                'verbose_name_plural': 'Результаты учеников',
                'ordering': ['-date_recorded', 'student'],
            },
        ),
    ]
