# Generated by Django 5.2.13 on 2026-04-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил норматив'),
        ),
        migrations.AddField(
            model_name='level',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='standards.standard', verbose_name='Норматив'),
        ),
        migrations.AddField(
            model_name='studentstandard',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='studentstandard',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='standards.standard', verbose_name='Норматив'),
        ),
        migrations.AddField(
            model_name='studentstandard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='students.student', verbose_name='Ученик'),
        ),
    ]
